In [1]:
import numpy as np

In [8]:
# We can create numpy array using np.array
a = np.array([1, 2, 3], float)
print(a)
print(type(a))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [9]:
# We can revert changes and create python array using np.array
a = a.tolist()
print(a)
print(type(a))

[1.0, 2.0, 3.0]
<class 'list'>


In [20]:
# Creating multi dimensional arrays
a = np.array([[1, 2, 3], [4, 5, 6]], int)
print(a, end='\n\n')

# Array slicing in python
print(a[0, :])
print(a[:, 0])

[[1 2 3]
 [4 5 6]]

[1 2 3]
[1 4]


In [24]:
# Array features
print(a.shape)
print(a.dtype)

(2, 3)
int64


In [43]:
# Array reshaping
print(a.reshape(3, 2), end='\n\n')
print(a.flatten())

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


In [57]:
# Creating arrays using numpy functions
print(np.arange(5), end = '\n\n')
print(np.arange(0, 4, 2), end = '\n\n')

print(np.ones((2, 3), int), end = '\n\n')
print(np.zeros((2, 3), int), end = '\n\n')

print(np.identity(4, int), end = '\n\n')
print(np.eye(4, k=2), end = '\n\n')

[0 1 2 3 4]

[0 2]

[[1 1 1]
 [1 1 1]]

[[0 0 0]
 [0 0 0]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [58]:
# A bit of training
a = np.array([[3, 5], [4, 8], [7, 9]], int)
for x in range(a.shape[0]):
    for y in range(a.shape[1]):
        print(a[x, y])

3
5
4
8
7
9


In [72]:
# Math operations on arrays
a = np.arange(1, 11)
b = np.arange(1, 20, 2)
print("Source:", a, b, sep='\n', end='\n\n')

print("a + b, a - b:", a + b, a - b, sep='\n', end='\n\n')
print("a * b, a / b:", a * b, a / b, sep='\n', end='\n\n')
print("a % b, a // b:", a % b, a // b, sep='\n', end='\n\n')
print("a ** b:", a ** b, sep='\n', end='\n\n')

Source:
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]

a + b, a - b:
[ 2  5  8 11 14 17 20 23 26 29]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]

a * b, a / b:
[  1   6  15  28  45  66  91 120 153 190]
[1.         0.66666667 0.6        0.57142857 0.55555556 0.54545455
 0.53846154 0.53333333 0.52941176 0.52631579]

a % b, a // b:
[ 0  2  3  4  5  6  7  8  9 10]
[1 0 0 0 0 0 0 0 0 0]

a ** b:
[                   1                    8                  243
                16384              1953125            362797056
          96889010407       35184372088832    16677181699666569
 -8446744073709551616]



In [82]:
# Rounding
a = np.arange(10, 70, 10)
a = np.sqrt(a)
print(a)

print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]
[3. 4. 5. 6. 7. 7.]
[4. 5. 6. 7. 8. 8.]
[3. 4. 5. 6. 7. 8.]


In [91]:
# Math operations on array elements
print("Array: ", a)

print("Summ:", a.sum())
print("Multiplication:", a.prod())

print("Mean value:", a.mean())
print("Dispersion:", a.var())
print("Standard Deviation:", a.std())

print("Min element:", a.min())
print("Min element index:", a.argmin())
print("Max element:", a.max())
print("Max element index:", a.argmax())

Array:  [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]
Summ: 34.25322901483669
Multiplication: 26832.815729997485
Mean value: 5.708871502472782
Dispersion: 2.4087861682541694
Standard Deviation: 1.552026471505615
Min element: 3.1622776601683795
Min element index: 0
Max element: 7.745966692414834
Max element index: 5


In [101]:
# Array comprehension
a = np.arange(10)
print("Array:", a)

a = a.clip(2, 7)
print("Clipped array:", a)
print("Unique elements:", np.unique(a))

Array: [0 1 2 3 4 5 6 7 8 9]
Clipped array: [2 2 2 3 4 5 6 7 7 7]
Unique elements: [2 3 4 5 6 7]


In [108]:
# Multidimensional arrays
a = np.array([[5, 2], [4, 1], [3, -1]], int)

print("Array:", a)
print("Mean values of columns", a.mean(axis=0))
print("Mean values of rows", a.mean(axis=1))

Array: [[ 5  2]
 [ 4  1]
 [ 3 -1]]
Mean values of columns [4.         0.66666667]
Mean values of rows [3.5 2.5 1. ]


In [114]:
# Logical operations on arrays
a = np.array([1, 2, 3])
b = np.array([1, 5, 7])

print("A greater or equal than B ?", a >= b)

A greater or equal than B ? [ True False False]
